port: /dev/ttyUSB0
baud: 1000000
rate: 100
sync_write: True
sync_read: False
read_rate: 10
write_rate: 10
 
joints: {
     joint_1: {id: 7, neutral: 512, min_angle: -90, max_angle: 90},
     joint_2: {id: 8, neutral: 512, min_angle: -90, max_angle: 90},
     joint_3: {id: 9, neutral: 512, min_angle: -90, max_angle: 90},
     joint_4: {id: 10, neutral: 512, min_angle: -90, max_angle: 90},
     joint_5: {id: 11, neutral: 512, min_angle: -90, max_angle: 90},
     joint_6: {id: 12, neutral: 512, min_angle: -90, max_angle: 90}
}
 
controllers: {
 
   right_arm_controller: {onboard: False, action_name: right_arm_controller/follow_joint_trajectory, type: follow_controller, joints: [ joint_1, joint_2, joint_3, joint_4, joint_5, joint_6]}
 
}
